# Generated by Django 3.2.9 on 2021-11-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(default='Bookmark', max_length=255, unique=True),
        ),
    ]
